services:
  - type: web
    name: ekamuthuapi
    runtime: docker
    repo: https://github.com/MLakshanD/ekamuthuAPI
    region: oregon
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 8080
